signing: major change to use app keys by default
danielfullmer/robotnix pull request #66
Opened 2020-12-08 08:44 UTC by danielfullmer

I've delayed pushing this breaking change to master until the next GrapheneOS release (likely today/tomorrow), so I can do a final test on my own personal device. Fixes part of the issues discussed in #24

We now use new application-specific keys and certificates for included apps
like Chromium / webview, Microg, and F-Droid, instead of relying on the
device-specific `releasekey`.  This allows us to share these keys between
multiple devices, push the same app updates to multiple devices, and remove an
ugly SELinux workaround for GrapheneOS that robotnix required.

Unfortunately, changing app keys will lose any data associated with those apps.
Fortunately, most data associated with those apps should be easy to re-create.
(Re-login to services in chromium, re-add F-Droid repos, etc.)
I hope to avoid breaking changes like this in the future by getting these
changes done relatively early in the projects' life.

If you've previously generated robotnix keys, you will need to do the
following to update to the new key directory layout: Move all keys and
certificates beginning with `com.android` from the device subdir (e.g.
`crosshatch`) under your `keyStorePath` to the parent directory. The files
beginning with `releasekey`, `platform`, `shared`, `media`, `networkstack`,
and `avb`/`verity` (if you have it) are device-specific, and should remain
under the device subdirectory.  For example, I ran the following command on my
machine:
 ```shell
$ mv /var/secrets/android-keys/crosshatch/com.android.* /var/secrets/android-keys/
 ```
After this, re-run `generateKeysScript` to create new application keys (e.g.
Chromium, F-Droid).

2020-12-08 17:20 UTC, hmenke requested changes

2020-12-08 17:20 UTC, hmenke commented on modules/apps/auditor.nix
> +        signatureFingerprint = config.apps.prebuilt.auditor.fingerprint;
Evaluation error
```suggestion
        signatureFingerprint = config.apps.prebuilt."Auditor".fingerprint;
```

2020-12-09 00:02 UTC, danielfullmer commented
Somewhat surprisingly, I didn't lose state when changing application keys. (checked MicroG and F-Droid) Perhaps it is because they are apps included in the system image...

2020-12-09 00:13 UTC, merged

2020-12-10 08:44 UTC, hmenke commented
No loss of state for me either.  Vanadium didn't even close my open tabs.

However, I noticed that a binary cache is urgently necessary.  My old garbage machine took a bit over 24 h to build this update (with existing ccache, although I don't know whether this helped at all) but only 9 h out of that were spent building my customized image.  The entire other 15 h were spent reproducing unpatched prebuilts like WebView and the kernel.  It would be really great if these could be published through a binary cache.  Maybe get in touch with @nix-community, they have [1 TB on Cachix](https://nix-community.org/#sponsors) or maybe contact Domen directly.  Since this is a task that doesn't require any technical expertise, I am also happy to reach out in place of the Robotnix project.

2020-12-14 00:42 UTC, danielfullmer commented
@hmenke
Thanks for the confirmation. I guess my mental model of how state was handled for system apps wasn't correct.

Can you confirm that F-Droid can still install applications in the background without prompting?  I expect it should work for you, but it didn't for me.  For some reason, F-Droid was somehow still using the old `releasekey` and not the new app `f-droid` key. I believe this was because I had previously pushed separately signed app updates to F-Droid via `adb install`. Running "Uninstall updates" on the "app info" settings page for F-Droid fixed my problem.

2020-12-14 01:12 UTC, danielfullmer commented
@hmenke Just pushed all kernels and browsers for the latest grapheneOS tag. See also https://github.com/danielfullmer/robotnix/issues/17#issuecomment-744108438

2020-12-14 08:20 UTC, hmenke commented
Ah, sorry, I can't comment on the F-Droid situation because I added new repos and deliberately wiped the F-Droid config to see if they show up the way I want.